export const mockRepos = [
    {
      id: 1,
      name: "Repo 1",
      forks_count: 10,
      open_issues_count: 5,
      watchers_count: 100,
      license: { name: "License A", url: "https://example.com/licenseA" },
      language: "English",
      archived: true,
      description: "This is description for Repo 1.",
    },
    {
      id: 2,
      name: "Repo 2",
      forks_count: 20,
      open_issues_count: 32,
      watchers_count: 200,
      license: { name: "License B", url: "https://example.com/licenseB" },
      language: "Spanish",
      archived: false,
      description: "Description for Repo 2.",
    },
    {
      id: 3,
      name: "Repo 3",
      forks_count: 1215,
      open_issues_count: 99,
      watchers_count: 150,
      license: { name: "License C", url: "https://example.com/licenseC" },
      language: "French",
      archived: true,
      description: "Repo 3 detailed description.",
    },
    {
      id: 4,
      name: "Repo 4",
      forks_count: 350,
      open_issues_count: 18,
      watchers_count: 300,
      license: { name: "License D", url: "https://example.com/licenseD" },
      language: "German",
      archived: false,
      description: "This is a description for Repo 4.",
    },
    {
      id: 5,
      name: "Repo 5",
      forks_count: 215,
      open_issues_count: 1,
      watchers_count: 250,
      license: { name: "License E", url: "https://example.com/licenseE" },
      language: "Italian",
      archived: true,
      description: "A unique description for Repo 5.",
    },
    {
      id: 6,
      name: "Repo 6",
      forks_count: 19,
      open_issues_count: 90,
      watchers_count: 110,
      license: { name: "License F", url: "https://example.com/licenseF" },
 
      archived: false,
      description: "Repo 6 special description.",
    },
    {
      id: 7,
      name: "Repo 7",
      forks_count: 210,
      open_issues_count: 3,
      watchers_count: 2080,
      license: { name: "License G", url: "https://example.com/licenseG" },

      archived: true,
      description: "Description text for Repo 7.",
    },
    {
      id: 8,
      name: "Repo 8",
      forks_count: 115,
      open_issues_count: 2,
      watchers_count: 1520,
      license: { name: "License H", url: "https://example.com/licenseH" },
   
      archived: false,
      description: "Detailed description of Repo 8.",
    },
    {
      id: 9,
      name: "Repo 9",
      forks_count: 30,
      open_issues_count: 8,
      watchers_count: 3020,
      license: { name: "License I", url: "https://example.com/licenseI" },
 
      archived: true,
      description: "Unique description for Repo 9.",
    },
    {
      id: 10,
      name: "Repo 10",
      forks_count: 25,
      open_issues_count: 4,
      watchers_count: 280,
      license: { name: "License J", url: "https://example.com/licenseJ" },
      language: "Arabic",
      archived: false,
      description: "Description for the Repo 10.",
    },
  ];
  
